import { Info, ExternalLink } from "lucide-react";
import type { HTMLAttributes } from "react";

// ─────────────────────────────────────────────
// Props
// ─────────────────────────────────────────────

export interface AiDisclaimerProps extends HTMLAttributes<HTMLDivElement> {
  /** Custom message to display instead of the default */
  message?: string;
  /** Show a link to the about page for more info */
  showLearnMore?: boolean;
  /** Visual variant */
  variant?: "banner" | "inline" | "compact";
}

// ─────────────────────────────────────────────
// Component
// ─────────────────────────────────────────────

export default function AiDisclaimer({
  message,
  showLearnMore = true,
  variant = "banner",
  className = "",
  ...rest
}: AiDisclaimerProps) {
  const defaultMessage =
    "This analysis was generated by AI and reviewed for accuracy. " +
    "Always read primary sources before making voting decisions.";

  const displayMessage = message ?? defaultMessage;

  if (variant === "compact") {
    return (
      <span
        className={`inline-flex items-center gap-1 text-xs text-amber-700 ${className}`}
        title={displayMessage}
        {...rest}
      >
        <Info size={12} aria-hidden="true" className="flex-shrink-0" />
        <span>AI-assisted</span>
      </span>
    );
  }

  if (variant === "inline") {
    return (
      <div
        role="note"
        aria-label="AI content disclaimer"
        className={[
          "flex items-start gap-2.5 text-xs text-amber-800 bg-amber-50",
          "border border-amber-200 rounded-lg px-3 py-2.5",
          className,
        ]
          .filter(Boolean)
          .join(" ")}
        {...rest}
      >
        <Info
          size={14}
          aria-hidden="true"
          className="flex-shrink-0 mt-0.5 text-amber-600"
        />
        <span className="leading-relaxed">
          {displayMessage}
          {showLearnMore && (
            <>
              {" "}
              <a
                href="/about#ai-methodology"
                className="font-medium underline underline-offset-2 hover:text-amber-900
                           focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-amber-500
                           rounded transition-colors whitespace-nowrap"
              >
                Learn more
                <ExternalLink
                  size={10}
                  className="inline ml-0.5 mb-0.5"
                  aria-hidden="true"
                />
              </a>
            </>
          )}
        </span>
      </div>
    );
  }

  // Default: banner variant
  return (
    <div
      role="note"
      aria-label="AI content disclaimer"
      className={[
        "w-full flex items-start gap-3 px-4 py-3",
        "bg-amber-50 border-l-4 border-amber-400",
        "text-sm text-amber-900",
        className,
      ]
        .filter(Boolean)
        .join(" ")}
      {...rest}
    >
      <Info
        size={18}
        aria-hidden="true"
        className="flex-shrink-0 mt-0.5 text-amber-500"
      />
      <div className="flex-1 min-w-0">
        <p className="font-semibold text-amber-800 mb-0.5">
          AI-Assisted Analysis
        </p>
        <p className="text-amber-700 leading-relaxed text-xs">
          {displayMessage}
          {showLearnMore && (
            <>
              {" "}
              <a
                href="/about#ai-methodology"
                className="font-medium underline underline-offset-2 hover:text-amber-900
                           focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-amber-500
                           rounded transition-colors whitespace-nowrap"
              >
                Our methodology
                <ExternalLink
                  size={10}
                  className="inline ml-0.5 mb-0.5"
                  aria-hidden="true"
                />
              </a>
            </>
          )}
        </p>
      </div>
    </div>
  );
}
