// ─────────────────────────────────────────────
// GET /api/cron/sync-voter-info
// Vercel Cron Job — seed/update voter registration info for all 50 states
// Schedule: weekly or before major elections (configure in vercel.json)
// ─────────────────────────────────────────────

import { prisma } from "@/lib/db";

/**
 * Static voter information for all 50 US states.
 * This data is based on well-known, publicly available state election policies.
 * Fields that are date-specific (registrationDeadline, earlyVotingStart, etc.)
 * are left null here since they change per election cycle. The textual fields
 * and boolean flags represent general state policy.
 */
interface StateVoterData {
  abbreviation: string;
  voterIdRequirements: string;
  onlineRegistration: boolean;
  sameDayRegistration: boolean;
  registrationUrl: string;
  stateElectionWebsite: string;
  pollingHoursStart: string;
  pollingHoursEnd: string;
  stateSOSName: string;
  stateSOSPhone: string;
  stateSOSEmail: string;
  additionalNotes: string;
}

const STATE_VOTER_DATA: StateVoterData[] = [
  {
    abbreviation: "AL",
    voterIdRequirements: "Strict photo ID required",
    onlineRegistration: false,
    sameDayRegistration: false,
    registrationUrl: "https://www.vote.org/register-to-vote/alabama/",
    stateElectionWebsite: "https://www.sos.alabama.gov/alabama-votes",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(334) 242-7210",
    stateSOSEmail: "elections@sos.alabama.gov",
    additionalNotes: "Registration deadline: 15 days before election.",
  },
  {
    abbreviation: "AK",
    voterIdRequirements: "Non-photo ID accepted; photo ID requested but not required",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://voterregistration.alaska.gov/",
    stateElectionWebsite: "https://www.elections.alaska.gov/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Division of Elections",
    stateSOSPhone: "(907) 465-4611",
    stateSOSEmail: "elections@alaska.gov",
    additionalNotes: "Registration deadline: 30 days before election. Same-day registration available.",
  },
  {
    abbreviation: "AZ",
    voterIdRequirements: "Strict photo ID required",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://azsos.gov/elections/voting-election/register-vote-or-update-your-current-voter-information",
    stateElectionWebsite: "https://azsos.gov/elections",
    pollingHoursStart: "6:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(602) 542-4285",
    stateSOSEmail: "elections@azsos.gov",
    additionalNotes: "Registration deadline: 29 days before election.",
  },
  {
    abbreviation: "AR",
    voterIdRequirements: "Photo ID requested",
    onlineRegistration: false,
    sameDayRegistration: false,
    registrationUrl: "https://www.vote.org/register-to-vote/arkansas/",
    stateElectionWebsite: "https://www.sos.arkansas.gov/elections",
    pollingHoursStart: "7:30 AM",
    pollingHoursEnd: "7:30 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(501) 682-1010",
    stateSOSEmail: "electioninfo@sos.arkansas.gov",
    additionalNotes: "Registration deadline: 30 days before election.",
  },
  {
    abbreviation: "CA",
    voterIdRequirements: "No ID required to vote at polls",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://registertovote.ca.gov/",
    stateElectionWebsite: "https://www.sos.ca.gov/elections",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(916) 657-2166",
    stateSOSEmail: "elections@sos.ca.gov",
    additionalNotes: "Registration deadline: 15 days before election. Conditional voter registration available on Election Day.",
  },
  {
    abbreviation: "CO",
    voterIdRequirements: "Photo ID or non-photo ID accepted",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://www.sos.state.co.us/voter/pages/pub/olvr/verifyNewVoter.xhtml",
    stateElectionWebsite: "https://www.sos.state.co.us/pubs/elections/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(303) 894-2200",
    stateSOSEmail: "elections@coloradosos.gov",
    additionalNotes: "Registration deadline: 8 days before election (by mail), same-day available in person. All-mail ballot state.",
  },
  {
    abbreviation: "CT",
    voterIdRequirements: "Non-photo ID accepted; photo ID requested",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://voterregistration.ct.gov/OLVR/",
    stateElectionWebsite: "https://portal.ct.gov/SOTS/Election-Services/",
    pollingHoursStart: "6:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Secretary of the State",
    stateSOSPhone: "(860) 509-6100",
    stateSOSEmail: "elections@ct.gov",
    additionalNotes: "Registration deadline: 7 days before election. Same-day registration available on Election Day.",
  },
  {
    abbreviation: "DE",
    voterIdRequirements: "Non-photo ID accepted",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://ivote.de.gov/VoterView",
    stateElectionWebsite: "https://elections.delaware.gov/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Commissioner of Elections",
    stateSOSPhone: "(302) 739-4277",
    stateSOSEmail: "elections@delaware.gov",
    additionalNotes: "Registration deadline: fourth Saturday before election.",
  },
  {
    abbreviation: "FL",
    voterIdRequirements: "Photo ID required",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://registertovoteflorida.gov/",
    stateElectionWebsite: "https://dos.fl.gov/elections/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Division of Elections",
    stateSOSPhone: "(850) 245-6200",
    stateSOSEmail: "DivElections@dos.myflorida.com",
    additionalNotes: "Registration deadline: 29 days before election.",
  },
  {
    abbreviation: "GA",
    voterIdRequirements: "Strict photo ID required",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://registertovote.sos.ga.gov/",
    stateElectionWebsite: "https://sos.ga.gov/elections-division",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(404) 656-2881",
    stateSOSEmail: "elections@sos.ga.gov",
    additionalNotes: "Registration deadline: fifth Monday before election (approximately 29 days).",
  },
  {
    abbreviation: "HI",
    voterIdRequirements: "Non-photo ID accepted",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://olvr.hawaii.gov/",
    stateElectionWebsite: "https://elections.hawaii.gov/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Office of Elections",
    stateSOSPhone: "(808) 453-8683",
    stateSOSEmail: "elections@hawaii.gov",
    additionalNotes: "All-mail election state. Same-day registration available at voter service centers.",
  },
  {
    abbreviation: "ID",
    voterIdRequirements: "Photo ID required",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://idahovotes.gov/online-voter-registration/",
    stateElectionWebsite: "https://idahovotes.gov/",
    pollingHoursStart: "8:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(208) 334-2852",
    stateSOSEmail: "elections@sos.idaho.gov",
    additionalNotes: "Registration deadline: 25 days before election. Same-day registration available on Election Day with photo ID.",
  },
  {
    abbreviation: "IL",
    voterIdRequirements: "No ID required to vote at polls",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://ova.elections.il.gov/",
    stateElectionWebsite: "https://www.elections.il.gov/",
    pollingHoursStart: "6:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "State Board of Elections",
    stateSOSPhone: "(217) 782-4141",
    stateSOSEmail: "webmaster@elections.il.gov",
    additionalNotes: "Registration deadline: 28 days before election (by mail). Grace period / same-day registration available.",
  },
  {
    abbreviation: "IN",
    voterIdRequirements: "Strict photo ID required",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://indianavoters.in.gov/",
    stateElectionWebsite: "https://www.in.gov/sos/elections/",
    pollingHoursStart: "6:00 AM",
    pollingHoursEnd: "6:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(317) 232-6531",
    stateSOSEmail: "elections@sos.in.gov",
    additionalNotes: "Registration deadline: 29 days before election.",
  },
  {
    abbreviation: "IA",
    voterIdRequirements: "Strict photo ID required",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://sos.iowa.gov/elections/voterreg/regtovoter/search.aspx",
    stateElectionWebsite: "https://sos.iowa.gov/elections/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "9:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(515) 281-0145",
    stateSOSEmail: "sos@sos.iowa.gov",
    additionalNotes: "Registration deadline: 15 days before election (by mail). Same-day registration available on Election Day.",
  },
  {
    abbreviation: "KS",
    voterIdRequirements: "Photo ID required",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://www.kdor.ks.gov/apps/voterreg/",
    stateElectionWebsite: "https://sos.ks.gov/elections/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(785) 296-4564",
    stateSOSEmail: "elections@sos.ks.gov",
    additionalNotes: "Registration deadline: 21 days before election.",
  },
  {
    abbreviation: "KY",
    voterIdRequirements: "Non-photo ID accepted; photo ID requested",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://vrsws.sos.ky.gov/ovrweb/",
    stateElectionWebsite: "https://elect.ky.gov/",
    pollingHoursStart: "6:00 AM",
    pollingHoursEnd: "6:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(502) 564-3490",
    stateSOSEmail: "elections@ky.gov",
    additionalNotes: "Registration deadline: 29 days before election.",
  },
  {
    abbreviation: "LA",
    voterIdRequirements: "Photo ID required",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://voterportal.sos.la.gov/VoterRegistration",
    stateElectionWebsite: "https://www.sos.la.gov/ElectionsAndVoting/",
    pollingHoursStart: "6:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(225) 922-0900",
    stateSOSEmail: "elections@sos.la.gov",
    additionalNotes: "Registration deadline: 30 days before election (in person), 20 days (online).",
  },
  {
    abbreviation: "ME",
    voterIdRequirements: "No ID required to vote at polls",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://www.maine.gov/sos/cec/elec/voter-info/voterregcard.html",
    stateElectionWebsite: "https://www.maine.gov/sos/cec/elec/",
    pollingHoursStart: "6:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(207) 624-7736",
    stateSOSEmail: "cec.elections@maine.gov",
    additionalNotes: "Same-day voter registration available on Election Day. Uses ranked-choice voting for federal races.",
  },
  {
    abbreviation: "MD",
    voterIdRequirements: "No ID required to vote at polls (first-time voters may need ID)",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://voterservices.elections.maryland.gov/OnlineVoterRegistration/",
    stateElectionWebsite: "https://elections.maryland.gov/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "State Board of Elections",
    stateSOSPhone: "(410) 269-2840",
    stateSOSEmail: "info.sbe@maryland.gov",
    additionalNotes: "Registration deadline: 21 days before election. Same-day registration during early voting.",
  },
  {
    abbreviation: "MA",
    voterIdRequirements: "No ID required for most voters",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://www.sec.state.ma.us/ovr/",
    stateElectionWebsite: "https://www.sec.state.ma.us/ele/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Secretary of the Commonwealth",
    stateSOSPhone: "(617) 727-2828",
    stateSOSEmail: "elections@sec.state.ma.us",
    additionalNotes: "Registration deadline: 10 days before election. Same-day registration available.",
  },
  {
    abbreviation: "MI",
    voterIdRequirements: "Photo ID requested (not strict; affidavit option available)",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://mvic.sos.state.mi.us/RegisterVoter",
    stateElectionWebsite: "https://mvic.sos.state.mi.us/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(517) 335-3234",
    stateSOSEmail: "elections@michigan.gov",
    additionalNotes: "Registration deadline: 15 days before election (online/mail). Same-day registration available at clerk's office.",
  },
  {
    abbreviation: "MN",
    voterIdRequirements: "Photo ID requested (not strict; vouching option available)",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://mnvotes.sos.mn.gov/VoterRegistration/",
    stateElectionWebsite: "https://www.sos.state.mn.us/elections-voting/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(651) 215-1440",
    stateSOSEmail: "elections.dept@state.mn.us",
    additionalNotes: "Registration deadline: 21 days before election (online/mail). Same-day registration on Election Day.",
  },
  {
    abbreviation: "MS",
    voterIdRequirements: "Strict photo ID required",
    onlineRegistration: false,
    sameDayRegistration: false,
    registrationUrl: "https://www.vote.org/register-to-vote/mississippi/",
    stateElectionWebsite: "https://www.sos.ms.gov/elections-voting",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(601) 359-1350",
    stateSOSEmail: "elections@sos.ms.gov",
    additionalNotes: "Registration deadline: 30 days before election. No online registration available.",
  },
  {
    abbreviation: "MO",
    voterIdRequirements: "Photo ID required",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://www.sos.mo.gov/elections/goVoteMissouri/register",
    stateElectionWebsite: "https://www.sos.mo.gov/elections",
    pollingHoursStart: "6:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(573) 751-2301",
    stateSOSEmail: "elections@sos.mo.gov",
    additionalNotes: "Registration deadline: fourth Wednesday before election (approximately 28 days).",
  },
  {
    abbreviation: "MT",
    voterIdRequirements: "Photo ID or non-photo ID accepted",
    onlineRegistration: false,
    sameDayRegistration: true,
    registrationUrl: "https://www.vote.org/register-to-vote/montana/",
    stateElectionWebsite: "https://sosmt.gov/elections/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(406) 444-2034",
    stateSOSEmail: "soselections@mt.gov",
    additionalNotes: "Registration deadline: 30 days before election (regular). Late registration available at county office through Election Day.",
  },
  {
    abbreviation: "NE",
    voterIdRequirements: "Photo ID requested (not strict)",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://www.nebraska.gov/apps-sos-voter-registration/",
    stateElectionWebsite: "https://sos.nebraska.gov/elections/",
    pollingHoursStart: "8:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(402) 471-2555",
    stateSOSEmail: "sos.elections@nebraska.gov",
    additionalNotes: "Registration deadline: third Friday before election (approximately 18 days). Second Friday before election for in-person.",
  },
  {
    abbreviation: "NV",
    voterIdRequirements: "Non-photo ID accepted",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://www.registertovotenv.gov/",
    stateElectionWebsite: "https://www.nvsos.gov/sos/elections",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(775) 684-5705",
    stateSOSEmail: "nvelect@sos.nv.gov",
    additionalNotes: "Registration deadline: 5th Sunday before election (approximately 28 days by mail). Same-day registration available.",
  },
  {
    abbreviation: "NH",
    voterIdRequirements: "Photo ID required (can sign affidavit if without)",
    onlineRegistration: false,
    sameDayRegistration: true,
    registrationUrl: "https://www.vote.org/register-to-vote/new-hampshire/",
    stateElectionWebsite: "https://www.sos.nh.gov/elections/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(603) 271-3242",
    stateSOSEmail: "elections@sos.nh.gov",
    additionalNotes: "Same-day voter registration available on Election Day. No advance registration deadline.",
  },
  {
    abbreviation: "NJ",
    voterIdRequirements: "No ID required for most voters",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://voter.svrs.nj.gov/register",
    stateElectionWebsite: "https://www.nj.gov/state/elections/",
    pollingHoursStart: "6:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Division of Elections",
    stateSOSPhone: "(609) 292-3760",
    stateSOSEmail: "elections@sos.nj.gov",
    additionalNotes: "Registration deadline: 21 days before election.",
  },
  {
    abbreviation: "NM",
    voterIdRequirements: "Non-photo ID accepted (name and address verification)",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://portal.sos.state.nm.us/OVR/",
    stateElectionWebsite: "https://www.sos.state.nm.us/voting-and-elections/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(505) 827-3600",
    stateSOSEmail: "sos.elections@state.nm.us",
    additionalNotes: "Registration deadline: 28 days before election. Same-day registration available during early voting and on Election Day.",
  },
  {
    abbreviation: "NY",
    voterIdRequirements: "No ID required for most voters",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://voterreg.dmv.ny.gov/MotorVoter/",
    stateElectionWebsite: "https://www.elections.ny.gov/",
    pollingHoursStart: "6:00 AM",
    pollingHoursEnd: "9:00 PM",
    stateSOSName: "State Board of Elections",
    stateSOSPhone: "(518) 474-6220",
    stateSOSEmail: "info@elections.ny.gov",
    additionalNotes: "Registration deadline: 25 days before election.",
  },
  {
    abbreviation: "NC",
    voterIdRequirements: "Photo ID required",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://www.ncsbe.gov/registering/how-register",
    stateElectionWebsite: "https://www.ncsbe.gov/",
    pollingHoursStart: "6:30 AM",
    pollingHoursEnd: "7:30 PM",
    stateSOSName: "State Board of Elections",
    stateSOSPhone: "(919) 814-0700",
    stateSOSEmail: "elections.sboe@ncsbe.gov",
    additionalNotes: "Registration deadline: 25 days before election. Same-day registration available during early voting period only.",
  },
  {
    abbreviation: "ND",
    voterIdRequirements: "Strict photo ID required (acceptable forms specified by law)",
    onlineRegistration: false,
    sameDayRegistration: true,
    registrationUrl: "https://www.vote.org/register-to-vote/north-dakota/",
    stateElectionWebsite: "https://vip.sos.nd.gov/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(701) 328-4146",
    stateSOSEmail: "soselect@nd.gov",
    additionalNotes: "North Dakota does not require voter registration. Voters need only a valid ID to vote.",
  },
  {
    abbreviation: "OH",
    voterIdRequirements: "Photo ID required",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://olvr.ohiosos.gov/",
    stateElectionWebsite: "https://www.ohiosos.gov/elections-voting/",
    pollingHoursStart: "6:30 AM",
    pollingHoursEnd: "7:30 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(614) 466-2585",
    stateSOSEmail: "election@ohiosos.gov",
    additionalNotes: "Registration deadline: 30 days before election.",
  },
  {
    abbreviation: "OK",
    voterIdRequirements: "Photo ID or voter registration card accepted",
    onlineRegistration: false,
    sameDayRegistration: false,
    registrationUrl: "https://www.vote.org/register-to-vote/oklahoma/",
    stateElectionWebsite: "https://oklahoma.gov/elections.html",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "State Election Board",
    stateSOSPhone: "(405) 521-2391",
    stateSOSEmail: "info@elections.ok.gov",
    additionalNotes: "Registration deadline: 25 days before election.",
  },
  {
    abbreviation: "OR",
    voterIdRequirements: "No ID required (all-mail voting state)",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://sos.oregon.gov/voting/Pages/registration.aspx",
    stateElectionWebsite: "https://sos.oregon.gov/voting/",
    pollingHoursStart: "N/A",
    pollingHoursEnd: "Ballots due by 8:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(503) 986-1518",
    stateSOSEmail: "elections.sos@oregon.gov",
    additionalNotes: "All-mail voting state. Registration deadline: 21 days before election.",
  },
  {
    abbreviation: "PA",
    voterIdRequirements: "ID required for first-time voters at a new polling place only",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://www.pavoterservices.pa.gov/Pages/VoterRegistrationApplication.aspx",
    stateElectionWebsite: "https://www.vote.pa.gov/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Department of State",
    stateSOSPhone: "(717) 787-5280",
    stateSOSEmail: "ra-elections@pa.gov",
    additionalNotes: "Registration deadline: 15 days before election.",
  },
  {
    abbreviation: "RI",
    voterIdRequirements: "Photo ID requested (provisional ballot available without)",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://vote.sos.ri.gov/",
    stateElectionWebsite: "https://vote.ri.gov/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(401) 222-2340",
    stateSOSEmail: "elections@sos.ri.gov",
    additionalNotes: "Registration deadline: 30 days before election.",
  },
  {
    abbreviation: "SC",
    voterIdRequirements: "Photo ID required (reasonable impediment affidavit available)",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://info.scvotes.sc.gov/eng/ovr/start.aspx",
    stateElectionWebsite: "https://www.scvotes.gov/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "State Election Commission",
    stateSOSPhone: "(803) 734-9060",
    stateSOSEmail: "elections@elections.sc.gov",
    additionalNotes: "Registration deadline: 30 days before election.",
  },
  {
    abbreviation: "SD",
    voterIdRequirements: "Photo ID required",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://sdsos.gov/elections-voting/voting/register-to-vote/",
    stateElectionWebsite: "https://sdsos.gov/elections-voting/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(605) 773-3537",
    stateSOSEmail: "elections@state.sd.us",
    additionalNotes: "Registration deadline: 15 days before election.",
  },
  {
    abbreviation: "TN",
    voterIdRequirements: "Strict photo ID required",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://ovr.govote.tn.gov/",
    stateElectionWebsite: "https://sos.tn.gov/elections",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(615) 741-7956",
    stateSOSEmail: "elections@tn.gov",
    additionalNotes: "Registration deadline: 30 days before election.",
  },
  {
    abbreviation: "TX",
    voterIdRequirements: "Strict photo ID required (alternatives with reasonable impediment declaration)",
    onlineRegistration: false,
    sameDayRegistration: false,
    registrationUrl: "https://www.vote.org/register-to-vote/texas/",
    stateElectionWebsite: "https://www.sos.texas.gov/elections/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(512) 463-5650",
    stateSOSEmail: "elections@sos.texas.gov",
    additionalNotes: "Registration deadline: 30 days before election. No online voter registration.",
  },
  {
    abbreviation: "UT",
    voterIdRequirements: "Photo ID or non-photo ID accepted",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://secure.utah.gov/voterreg/",
    stateElectionWebsite: "https://voteinfo.utah.gov/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Lieutenant Governor",
    stateSOSPhone: "(801) 538-1041",
    stateSOSEmail: "elections@utah.gov",
    additionalNotes: "Registration deadline: 11 days before election (online/mail). Same-day registration available. All-mail voting state.",
  },
  {
    abbreviation: "VT",
    voterIdRequirements: "No ID required to vote at polls",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://olvr.vermont.gov/",
    stateElectionWebsite: "https://sos.vermont.gov/elections/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(802) 828-2363",
    stateSOSEmail: "elections@vermont.gov",
    additionalNotes: "Same-day voter registration available on Election Day.",
  },
  {
    abbreviation: "VA",
    voterIdRequirements: "Photo ID accepted or free voter photo ID card available",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://vote.elections.virginia.gov/VoterInformation",
    stateElectionWebsite: "https://www.elections.virginia.gov/",
    pollingHoursStart: "6:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Department of Elections",
    stateSOSPhone: "(804) 864-8901",
    stateSOSEmail: "info@elections.virginia.gov",
    additionalNotes: "Registration deadline: 22 days before election (online/mail). Same-day registration available.",
  },
  {
    abbreviation: "WA",
    voterIdRequirements: "No ID required (all-mail voting state)",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://voter.votewa.gov/WhereToVote.aspx",
    stateElectionWebsite: "https://www.sos.wa.gov/elections/",
    pollingHoursStart: "N/A",
    pollingHoursEnd: "Ballots due by 8:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(360) 902-4180",
    stateSOSEmail: "elections@sos.wa.gov",
    additionalNotes: "All-mail voting state. Registration deadline: 8 days before election (online/mail). Same-day registration in person.",
  },
  {
    abbreviation: "WV",
    voterIdRequirements: "Non-photo ID accepted (various forms)",
    onlineRegistration: true,
    sameDayRegistration: false,
    registrationUrl: "https://ovr.sos.wv.gov/Register",
    stateElectionWebsite: "https://sos.wv.gov/elections/",
    pollingHoursStart: "6:30 AM",
    pollingHoursEnd: "7:30 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(304) 558-6000",
    stateSOSEmail: "elections@wvsos.com",
    additionalNotes: "Registration deadline: 21 days before election.",
  },
  {
    abbreviation: "WI",
    voterIdRequirements: "Strict photo ID required",
    onlineRegistration: true,
    sameDayRegistration: true,
    registrationUrl: "https://myvote.wi.gov/en-us/Register-To-Vote",
    stateElectionWebsite: "https://elections.wi.gov/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "8:00 PM",
    stateSOSName: "Wisconsin Elections Commission",
    stateSOSPhone: "(608) 266-8005",
    stateSOSEmail: "elections@wi.gov",
    additionalNotes: "Registration deadline: 20 days before election (by mail). Same-day registration available with proof of residence.",
  },
  {
    abbreviation: "WY",
    voterIdRequirements: "Photo ID or non-photo ID accepted",
    onlineRegistration: false,
    sameDayRegistration: true,
    registrationUrl: "https://www.vote.org/register-to-vote/wyoming/",
    stateElectionWebsite: "https://sos.wyo.gov/Elections/",
    pollingHoursStart: "7:00 AM",
    pollingHoursEnd: "7:00 PM",
    stateSOSName: "Secretary of State",
    stateSOSPhone: "(307) 777-5860",
    stateSOSEmail: "elections@wyo.gov",
    additionalNotes: "Same-day voter registration available on Election Day. Registration closes 14 days before election for mail/online.",
  },
];

export async function GET(request: Request) {
  const authHeader = request.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    // Fetch all states from the database for abbreviation → id lookup
    const states = await prisma.state.findMany({
      select: { id: true, abbreviation: true },
    });
    const stateByAbbreviation = new Map(
      states.map((s) => [s.abbreviation.toUpperCase(), s.id])
    );

    let upserted = 0;
    let skipped = 0;
    const errors: string[] = [];

    for (const data of STATE_VOTER_DATA) {
      const stateId = stateByAbbreviation.get(data.abbreviation);
      if (!stateId) {
        errors.push(`State not found in database: ${data.abbreviation}`);
        skipped++;
        continue;
      }

      try {
        await prisma.voterInfo.upsert({
          where: { stateId },
          create: {
            stateId,
            voterIdRequirements: data.voterIdRequirements,
            onlineRegistration: data.onlineRegistration,
            sameDayRegistration: data.sameDayRegistration,
            registrationUrl: data.registrationUrl,
            stateElectionWebsite: data.stateElectionWebsite,
            pollingHoursStart: data.pollingHoursStart,
            pollingHoursEnd: data.pollingHoursEnd,
            stateSOSName: data.stateSOSName,
            stateSOSPhone: data.stateSOSPhone,
            stateSOSEmail: data.stateSOSEmail,
            additionalNotes: data.additionalNotes,
          },
          update: {
            voterIdRequirements: data.voterIdRequirements,
            onlineRegistration: data.onlineRegistration,
            sameDayRegistration: data.sameDayRegistration,
            registrationUrl: data.registrationUrl,
            stateElectionWebsite: data.stateElectionWebsite,
            pollingHoursStart: data.pollingHoursStart,
            pollingHoursEnd: data.pollingHoursEnd,
            stateSOSName: data.stateSOSName,
            stateSOSPhone: data.stateSOSPhone,
            stateSOSEmail: data.stateSOSEmail,
            additionalNotes: data.additionalNotes,
          },
        });
        upserted++;
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        errors.push(`Failed to upsert ${data.abbreviation}: ${message}`);
        skipped++;
      }
    }

    console.log(
      `[cron/sync-voter-info] Sync complete: ${upserted} upserted, ${skipped} skipped`
    );

    return Response.json({
      synced: upserted,
      skipped,
      total: STATE_VOTER_DATA.length,
      errors: errors.length > 0 ? errors : undefined,
      message: "Voter info sync completed successfully",
    });
  } catch (error) {
    console.error("[cron/sync-voter-info] Error:", error);
    return Response.json({ error: "Sync failed" }, { status: 500 });
  }
}
